import React, { useState, useEffect, useContext, useRef } from 'react';
import { Search, Download, Printer, FileText } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { AuthContext } from '../../../../context/AuthContext';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { fetchWithAuth } from '../../../../utils/api.js';
import InvoiceTemplate from '../../../../Component/InvoiceTemplate';
import InvoiceActions from '../../../../Component/InvoiceActions';

export default function EmployeeOrders() {
  const { user } = useContext(AuthContext);
  const [searchQuery, setSearchQuery] = useState('');
  const [orders, setOrders] = useState([]);

  const [selectedInvoice, setSelectedInvoice] = useState(null);
  const invoiceRef = useRef(null);

  useEffect(() => {
    if (user?.userId) {
      fetchWithAuth(`${import.meta.env.VITE_API_BASE_URL}/api/sales/orders/${user.userId}`)
        .then(res => res.json())
        .then(data => {
          if (data.success) {
            setOrders(data.data);
          }
        })
        .catch(err => console.error("Failed to fetch order history", err));
    }
  }, [user]);

  const filteredOrders = orders.filter(order => 
    (order.invoiceNumber && order.invoiceNumber.toLowerCase().includes(searchQuery.toLowerCase())) || 
    (order.customerName && order.customerName.toLowerCase().includes(searchQuery.toLowerCase()))
  );

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:justify-between md:items-end gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">My Order History</h1>
          <p className="text-slate-500">View and reprint invoices generated by you.</p>
        </div>
        
        {/* Search */}
        <div className="relative w-full md:w-80">
          <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <Search size={18} className="text-slate-400" />
          </div>
          <input
            type="text"
            className="block w-full pl-10 pr-3 py-2 border border-slate-200 rounded-xl focus:ring-indigo-500 focus:border-indigo-500 bg-white shadow-sm"
            placeholder="Search Invoice No or Customer..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
        </div>
      </div>

      <div className="bg-indigo-50 border border-indigo-200 text-indigo-800 p-4 rounded-xl flex items-start gap-3">
        <FileText size={20} className="shrink-0 mt-0.5" />
        <div className="text-sm">
          <strong>Personal Ledger:</strong> This view is restricted to sales processed by you. If a customer needs a duplicate receipt for a warranty claim, you can reprint it here without needing Store Admin approval.
        </div>
      </div>

      {/* Orders Table */}
      <motion.div 
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden"
      >
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm whitespace-nowrap">
            <thead className="bg-slate-50 text-slate-600 font-medium">
              <tr>
                <th className="px-6 py-4">Date</th>
                <th className="px-6 py-4">Invoice No</th>
                <th className="px-6 py-4">Customer Name</th>
                <th className="px-6 py-4 text-right">Amount</th>
                <th className="px-6 py-4 text-center">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredOrders.length > 0 ? (
                filteredOrders.map((order) => (
                  <tr key={order._id} className="hover:bg-slate-50 transition-colors">
                    <td className="px-6 py-4 text-slate-600">
                      {new Date(order.createdAt).toLocaleString()}
                    </td>
                    <td className="px-6 py-4 font-bold text-indigo-600">
                      {order.invoiceNumber}
                    </td>
                    <td className="px-6 py-4 font-medium text-slate-800">
                      {order.customerName || 'Walk-in Customer'}
                    </td>
                    <td className="px-6 py-4 text-right font-bold text-slate-800">
                      ₹{order.amount.toLocaleString()}
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center justify-center gap-2">
                        <button 
                          onClick={() => setSelectedInvoice(order)}
                          className="flex items-center gap-1 text-slate-600 hover:text-indigo-600 px-3 py-1.5 rounded-lg hover:bg-indigo-50 transition-colors border border-transparent hover:border-indigo-100 text-xs font-medium"
                        >
                          <FileText size={14} /> View Invoice
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="5" className="px-6 py-8 text-center text-slate-500">
                    No orders found matching your search.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </motion.div>

      {/* Invoice Modal */}
      <AnimatePresence>
        {selectedInvoice && (
          <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <motion.div 
              initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.95, opacity: 0 }}
              className="bg-white rounded-2xl shadow-2xl w-full max-w-4xl overflow-hidden flex flex-col max-h-[90vh]"
            >
              <div className="p-6 border-b border-slate-100 flex justify-between items-start bg-indigo-50" data-no-print>
                <div className="flex gap-3">
                  <div className="w-10 h-10 bg-indigo-500 text-white rounded-full flex items-center justify-center shrink-0">
                    <FileText size={24} />
                  </div>
                  <div>
                    <h3 className="font-bold text-lg text-indigo-900">Invoice {selectedInvoice.invoiceNumber}</h3>
                    <p className="text-indigo-700 text-sm">Past Order Record</p>
                  </div>
                </div>
                <button onClick={() => setSelectedInvoice(null)} className="text-slate-400 hover:text-slate-600">✕</button>
              </div>

              <div className="p-8 flex-1 overflow-y-auto bg-white flex justify-center w-full">
                <div className="w-full" ref={invoiceRef}>
                  <InvoiceTemplate invoice={selectedInvoice} storeData={{ storeName: 'Techhansa Retail' }} />
                </div>
              </div>
              
              {/* Action Buttons: Close + Download + WhatsApp + Print */}
              <div className="flex items-center justify-between border-t border-slate-100 bg-slate-50 px-4 py-3" data-no-print>
                <button onClick={() => setSelectedInvoice(null)} className="px-4 py-2 text-slate-600 font-medium hover:bg-slate-200 rounded-xl transition-colors">Close</button>
                <div className="flex gap-3">
                  <InvoiceActions invoice={selectedInvoice} storeData={{ storeName: 'Techhansa Retail' }} invoiceRef={invoiceRef} />
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

    </div>
  );
}
