import React, { useState, useEffect, useContext } from 'react';
import { Search, Download, Printer, FileText } from 'lucide-react';
import { motion } from 'framer-motion';
import { AuthContext } from '../../../../context/AuthContext';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function EmployeeOrders() {
  const { user } = useContext(AuthContext);
  const [searchQuery, setSearchQuery] = useState('');
  const [orders, setOrders] = useState([]);

  useEffect(() => {
    if (user?.userId) {
      fetch(`${import.meta.env.VITE_API_BASE_URL}/api/sales/orders/${user.userId}`)
        .then(res => res.json())
        .then(data => {
          if (data.success) {
            setOrders(data.data);
          }
        })
        .catch(err => console.error("Failed to fetch order history", err));
    }
  }, [user]);

  const filteredOrders = orders.filter(order => 
    (order.invoiceNumber && order.invoiceNumber.toLowerCase().includes(searchQuery.toLowerCase())) || 
    (order.customerName && order.customerName.toLowerCase().includes(searchQuery.toLowerCase()))
  );

  const generatePDF = (order, autoPrint = false) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.text("Techhansa Retail", 14, 22);
    doc.setFontSize(12);
    doc.text("Customer Invoice", 14, 32);
    
    // Invoice details
    doc.setFontSize(10);
    doc.text(`Invoice No: ${order.invoiceNumber}`, 14, 45);
    doc.text(`Date: ${new Date(order.createdAt).toLocaleString()}`, 14, 52);
    doc.text(`Customer Name: ${order.customerName || 'Walk-in'}`, 14, 59);
    doc.text(`Phone: ${order.customerPhone || 'N/A'}`, 14, 66);
    
    const tableBody = (order.items || []).map(item => {
      const itemName = item.serialNumbers && item.serialNumbers.length > 0
        ? `${item.name}\n(SN: ${item.serialNumbers.join(', ')})`
        : item.name;
      return [
        itemName,
        item.quantity,
        `Rs. ${(item.sellingPrice || 0).toLocaleString()}`,
        `Rs. ${(item.quantity * (item.sellingPrice || 0)).toLocaleString()}`
      ];
    });
    
    autoTable(doc, {
      startY: 75,
      head: [['Item Name', 'Qty', 'Price', 'Total']],
      body: tableBody,
      theme: 'grid',
      headStyles: { fillColor: [79, 70, 229] }
    });
    
    const finalY = (doc.lastAutoTable ? doc.lastAutoTable.finalY : 75) + 10;
    
    autoTable(doc, {
      startY: finalY,
      body: [
        ['Subtotal', `Rs. ${(order.subtotalAmount || 0).toLocaleString()}`],
        ['Tax (18% GST)', `Rs. (((order.amount || 0) - (order.subtotalAmount || 0))).toLocaleString()`],
        ['Grand Total', `Rs. ${(order.amount || 0).toLocaleString()}`]
      ],
      theme: 'plain',
      styles: { halign: 'right' },
      columnStyles: { 0: { fontStyle: 'bold' } }
    });

    if (autoPrint) {
      doc.autoPrint();
      window.open(doc.output('bloburl'), '_blank');
    } else {
      doc.save(`${order.invoiceNumber}.pdf`);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:justify-between md:items-end gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">My Order History</h1>
          <p className="text-slate-500">View and reprint invoices generated by you.</p>
        </div>
        
        {/* Search */}
        <div className="relative w-full md:w-80">
          <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <Search size={18} className="text-slate-400" />
          </div>
          <input
            type="text"
            className="block w-full pl-10 pr-3 py-2 border border-slate-200 rounded-xl focus:ring-indigo-500 focus:border-indigo-500 bg-white shadow-sm"
            placeholder="Search Invoice No or Customer..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
        </div>
      </div>

      <div className="bg-indigo-50 border border-indigo-200 text-indigo-800 p-4 rounded-xl flex items-start gap-3">
        <FileText size={20} className="shrink-0 mt-0.5" />
        <div className="text-sm">
          <strong>Personal Ledger:</strong> This view is restricted to sales processed by you. If a customer needs a duplicate receipt for a warranty claim, you can reprint it here without needing Store Admin approval.
        </div>
      </div>

      {/* Orders Table */}
      <motion.div 
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden"
      >
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm whitespace-nowrap">
            <thead className="bg-slate-50 text-slate-600 font-medium">
              <tr>
                <th className="px-6 py-4">Date</th>
                <th className="px-6 py-4">Invoice No</th>
                <th className="px-6 py-4">Customer Name</th>
                <th className="px-6 py-4 text-right">Amount</th>
                <th className="px-6 py-4 text-center">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredOrders.length > 0 ? (
                filteredOrders.map((order) => (
                  <tr key={order._id} className="hover:bg-slate-50 transition-colors">
                    <td className="px-6 py-4 text-slate-600">
                      {new Date(order.createdAt).toLocaleString()}
                    </td>
                    <td className="px-6 py-4 font-bold text-indigo-600">
                      {order.invoiceNumber}
                    </td>
                    <td className="px-6 py-4 font-medium text-slate-800">
                      {order.customerName || 'Walk-in Customer'}
                    </td>
                    <td className="px-6 py-4 text-right font-bold text-slate-800">
                      ₹{order.amount.toLocaleString()}
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center justify-center gap-2">
                        <button 
                          onClick={() => generatePDF(order)}
                          className="flex items-center gap-1 text-slate-600 hover:text-indigo-600 px-3 py-1.5 rounded-lg hover:bg-indigo-50 transition-colors border border-transparent hover:border-indigo-100 text-xs font-medium"
                        >
                          <Download size={14} /> Download
                        </button>
                        <button 
                          onClick={() => generatePDF(order, true)}
                          className="flex items-center gap-1 text-slate-600 hover:text-indigo-600 px-3 py-1.5 rounded-lg hover:bg-indigo-50 transition-colors border border-transparent hover:border-indigo-100 text-xs font-medium"
                        >
                          <Printer size={14} /> Print Bill
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="5" className="px-6 py-8 text-center text-slate-500">
                    No orders found matching your search.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </motion.div>

    </div>
  );
}
